---
apiVersion: v1
kind: Secret
metadata:
  - name: rds-secret
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdDEyMzQ1

---
kind: ConfigMap
apiVersion: v1
metadata:
  - name: pods-configmap
data:
  # Configuration values can be set as key-value properties
  DB_DATABASE: todo
  DB_HOST: "terraform-20221028174056094400000001.ck8j652xydqj.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  # DB_USERNAME: root
  # DB_PASSWORD: root12345

---
kind: Pod
apiVersion: v1
metadata:
  - name: db-baseline
  labels:
    app: db-baseline
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  containers:
    - name: db-baseline
      image: csye7125fall2022group03/dockrepo:dbmigrationimage
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: DB_USERNAME
        envFrom:
          - configMapRef:
              name: pods-configmap
      command: ["flyway", "baseline", "-baselineVersion=0"]